### ISSUE TITLE
error: driftdb-worker should only be compiled to WebAssembly. Use driftdb-server for other targets.

### ISSUE THREAD

**Issue by yonas** [drifting-in-space/driftdb#19]
```
$ git clone ...
$ cd driftdb
$ cargo build --release
...
   Compiling worker-macros v0.0.6
   Compiling worker v0.0.11
   Compiling driftdb-server v0.1.1 (/memfs/git/driftdb/driftdb-server)
   Compiling driftdb-worker v0.1.1 (/memfs/git/driftdb/driftdb-worker)
error: driftdb-worker should only be compiled to WebAssembly. Use driftdb-server for other targets.
   --> driftdb-worker/src/lib.rs:102:1
    |
102 | / compile_error!(
103 | |     "driftdb-worker should only be compiled to WebAssembly. Use driftdb-server for other targets."
104 | | );
    | |_^

error: could not compile `driftdb-worker` due to previous error
warning: build failed, waiting for other jobs to finish...
```

OS: FreeBSD 13.1-RELEASE-p5
cargo 1.66.1

**Comment by paulgb** [comment]
Thanks for reporting.

I see, the problem is that `driftdb-worker` is the Cloudflare Worker, so it is designed to only compiled to WebAssembly. The `compiler_error` there corresponds to [this guard](https://github.com/drifting-in-space/driftdb/blob/af64f62b29a0baae09a7d450affa9e69ba61b000/driftdb-worker/src/lib.rs#L103), that was placed there intentionally because the worker does some things that are not thread-safe (WebAssembly is single-threaded so this isn’t a problem as long as we restrict the target to WebAssembly).

For now, a workaround is that you can run `cargo build` in the `driftdb-server` directory instead and it should work.

It would be nice if `cargo build` worked in the root, though. I’m not sure if there is a way to make it work. If nothing else, we should document this better, because running `cargo build` probably is the first thing somebody does after cloning the repo.
