### ISSUE TITLE
How to protect API token ?

### ISSUE THREAD

**Issue by viticis** [drifting-in-space/driftdb#35]
I had signed up a api token for testing DriftDB, it's really wonderful product.
But in the network dev-tool, we can see the api token, And anyone can use it.
Is there some way to protect the token?
Thanks.

**Comment by paulgb** [comment]
Hi @viticis

Good question, we should address this in the docs.

The answer is that the API token is expected to be public, so it's fine to use it in public code. All somebody can do with it is create new rooms (there's no way to, for example, list existing rooms, by design). Eventually we may scope API tokens to be associated with one website using CORS headers, so that somebody can't take your API token and use it on their own site, but if we do that we will contact everyone affected with plenty of notice first.

**Comment by viticis** [comment]
Thank you for your reply.
In fact, when I sign up for an API token, it needs to enter a website. I thought it was for CORS at the time, but it wasn't.
But if Jamsocket.live is to be a SAAS product, I think the public token can't tell which ones are from real paid developers.
Thanks again.

**Comment by paulgb** [comment]
I've updated the email sent to users who sign up to jamsocket.live to provide clarification here. Thanks again for flagging this.
